inbounds:
- listen: /dev/shm/grpc.socket,0666
  protocol: trojan
  tag: grpc
  settings:
    clients:
    - password: "passwd"
  streamSettings:
    network: grpc
    grpcSettings:
      serviceName: grpc

outbounds:
- tag: direct
  protocol: freedom
  domainStrategy: UseIPv4
- tag: blocked
  protocol: blackhole

routing:
  domainStrategy: AsIs
  rules:
  - type: field
    ip:
    - geoip:private
    domain:
    - geosite:category-ads-all
    outboundTag: blocked
