---
log:
  loglevel: info
  access: "/var/log/xray/access.log"
  error: "/var/log/xray/error.log"
routing:
  domainStrategy: IPIfNonMatch
  rules:
  - type: field
    ip:
    - geoip:cn
    - geoip:private
    outboundTag: block
inbounds:
- listen: 0.0.0.0
  port: 443
  protocol: vless
  settings:
    clients:
    - id: "passwd"
      flow: ""
    decryption: none
  streamSettings:
    network: grpc
    security: reality
    realitySettings:
      show: false
      dest: www.example.com:443
      xver: 0
      serverNames:
      - www.example.com
      privateKey: "private_key"
      shortIds:
      - ""
      - a1
    grpcSettings:
      serviceName: grpc
outbounds:
- protocol: freedom
  tag: direct
- protocol: blackhole
  tag: block
