name: update
on:
#  schedule:
#    - cron: "0 0 * * *"
  watch:
      types: started
jobs:
  build:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out project files
        uses: actions/checkout@v3
  
      - name: Check and upload
        run: |
          python3 build.py "${{ secrets.GITHUB_TOKEN }}"
