name: update
on:
  schedule:
    - cron: "0 0 * * *"
  watch:
      types: started
jobs:
  build:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out project files
        uses: actions/checkout@v3

      - name: sh-checker
        run: |
          ver=$(wget -qO- https://api.github.com/repos/mvdan/sh/releases/latest | awk -F'"' '/tag_name/{print$4}')
          ver_local=$(./tools/shfmt -version)
          if [ "$ver" == "$ver_local" ]; then
            exit 0
          fi
          wget -q https://github.com/mvdan/sh/releases/latest/download/shfmt_"$ver"_linux_amd64 -O tools/shfmt
          chmod +x tools/shfmt
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -am "tools/shfmt: ${ver_local} -> ${ver}"
          git push
  
      - name: Check and upload
        run: |
          dpkg --version
          python3 build.py
